export interface Order {
  asset_Class: string;
  asset_Id: string;
  // canceled_at?: string;
  client_Order_Id: string;
  created_At: string;
  // expired_at?: string;
  extended_Hours: false;
  // failed_at?: string;
  // filled_at?: string;
  // filled_avg_price?: string;
  filled_Qty: string;
  // hwm?: string;
  id: string;
  // legs: null;
  limit_Price: string;
  // notional: null;
  order_Class: string;
  order_Type: string;
  qty: string;
  // replaced_at: null;
  // replaced_by: null;
  // replaces: null;
  side: string;
  // source: null;
  status: string;
  // stop_price: null;
  submitted_At: string;
  // subtag: null;
  symbol: string;
  time_In_Force: string;
  // trail_percent: null;
  // trail_price: null;
  type: string;
  updated_At: string;
}
